# ============================================================
#   QUESTION BANK – Edit this file to add/modify questions
# ============================================================

ALL_APTITUDE_QUESTIONS = [

    # ==================== EASY (65 questions) ====================
    {"difficulty": "Easy", "question": "What is the next number in the series: 2, 4, 8, 16, ?", "options": {"A": "18", "B": "24", "C": "32", "D": "64"}, "answer": "C"},
    {"difficulty": "Easy", "question": "Which number is missing: 1, 4, 9, 16, ?", "options": {"A": "20", "B": "24", "C": "25", "D": "36"}, "answer": "C"},
    {"difficulty": "Easy", "question": "What is the next number: 3, 6, 12, 24, ?", "options": {"A": "36", "B": "48", "C": "42", "D": "30"}, "answer": "B"},
    {"difficulty": "Easy", "question": "Find the missing number: 5, 10, 20, 40, ?", "options": {"A": "60", "B": "70", "C": "80", "D": "50"}, "answer": "C"},
    {"difficulty": "Easy", "question": "What comes next: 1, 3, 6, 10, 15, ?", "options": {"A": "18", "B": "21", "C": "20", "D": "19"}, "answer": "B"},
    {"difficulty": "Easy", "question": "Next in series: 7, 14, 21, 28, ?", "options": {"A": "32", "B": "35", "C": "36", "D": "42"}, "answer": "B"},
    {"difficulty": "Easy", "question": "What is 15% of 200?", "options": {"A": "20", "B": "25", "C": "30", "D": "35"}, "answer": "C"},
    {"difficulty": "Easy", "question": "What does CPU stand for?", "options": {"A": "Central Process Unit", "B": "Control Processing Unit", "C": "Central Processing Unit", "D": "Core Processing Unit"}, "answer": "C"},
    {"difficulty": "Easy", "question": "Which symbol is used for comments in Python?", "options": {"A": "//", "B": "/*", "C": "#", "D": "--"}, "answer": "C"},
    {"difficulty": "Easy", "question": "What does RAM stand for?", "options": {"A": "Random Access Memory", "B": "Read Access Memory", "C": "Rapid Access Module", "D": "Random Allocation Memory"}, "answer": "A"},
    {"difficulty": "Easy", "question": "Which data structure uses LIFO order?", "options": {"A": "Queue", "B": "Stack", "C": "Array", "D": "Tree"}, "answer": "B"},
    {"difficulty": "Easy", "question": "What is 25% of 400?", "options": {"A": "75", "B": "100", "C": "125", "D": "150"}, "answer": "B"},
    {"difficulty": "Easy", "question": "Which one is different: Apple, Mango, Banana, Carrot?", "options": {"A": "Apple", "B": "Mango", "C": "Banana", "D": "Carrot"}, "answer": "D"},
    {"difficulty": "Easy", "question": "Book is to Reading as Fork is to ?", "options": {"A": "Kitchen", "B": "Eating", "C": "Cooking", "D": "Food"}, "answer": "B"},
    {"difficulty": "Easy", "question": "What is the LCM of 4 and 6?", "options": {"A": "8", "B": "10", "C": "12", "D": "24"}, "answer": "C"},
    {"difficulty": "Easy", "question": "What is the HCF of 12 and 18?", "options": {"A": "3", "B": "6", "C": "9", "D": "12"}, "answer": "B"},
    {"difficulty": "Easy", "question": "A train travels 60 km in 1 hour. How far in 30 minutes?", "options": {"A": "15 km", "B": "20 km", "C": "30 km", "D": "60 km"}, "answer": "C"},
    {"difficulty": "Easy", "question": "Which letter comes next: A, C, E, G, ?", "options": {"A": "H", "B": "I", "C": "J", "D": "K"}, "answer": "B"},
    {"difficulty": "Easy", "question": "What is 10 x 10?", "options": {"A": "10", "B": "100", "C": "1000", "D": "20"}, "answer": "B"},
    {"difficulty": "Easy", "question": "How many sides does a hexagon have?", "options": {"A": "5", "B": "6", "C": "7", "D": "8"}, "answer": "B"},
    {"difficulty": "Easy", "question": "What is the square root of 144?", "options": {"A": "10", "B": "11", "C": "12", "D": "13"}, "answer": "C"},
    {"difficulty": "Easy", "question": "Which planet is closest to the sun?", "options": {"A": "Venus", "B": "Earth", "C": "Mercury", "D": "Mars"}, "answer": "C"},
    {"difficulty": "Easy", "question": "What is 50% of 80?", "options": {"A": "30", "B": "35", "C": "40", "D": "45"}, "answer": "C"},
    {"difficulty": "Easy", "question": "If today is Monday, what day is after 3 days?", "options": {"A": "Wednesday", "B": "Thursday", "C": "Friday", "D": "Tuesday"}, "answer": "B"},
    {"difficulty": "Easy", "question": "What is 7 x 8?", "options": {"A": "54", "B": "56", "C": "58", "D": "60"}, "answer": "B"},
    {"difficulty": "Easy", "question": "What comes next: 10, 20, 30, 40, ?", "options": {"A": "45", "B": "50", "C": "55", "D": "60"}, "answer": "B"},
    {"difficulty": "Easy", "question": "Which is the largest ocean?", "options": {"A": "Atlantic", "B": "Indian", "C": "Arctic", "D": "Pacific"}, "answer": "D"},
    {"difficulty": "Easy", "question": "How many minutes are in 2 hours?", "options": {"A": "100", "B": "110", "C": "120", "D": "130"}, "answer": "C"},
    {"difficulty": "Easy", "question": "What is 100 - 37?", "options": {"A": "63", "B": "67", "C": "73", "D": "57"}, "answer": "A"},
    {"difficulty": "Easy", "question": "Which number is even: 13, 17, 22, 25?", "options": {"A": "13", "B": "17", "C": "22", "D": "25"}, "answer": "C"},
    {"difficulty": "Easy", "question": "What is the next: 1, 1, 2, 3, 5, 8, ?", "options": {"A": "11", "B": "12", "C": "13", "D": "14"}, "answer": "C"},
    {"difficulty": "Easy", "question": "A dozen equals how many?", "options": {"A": "10", "B": "12", "C": "14", "D": "16"}, "answer": "B"},
    {"difficulty": "Easy", "question": "What is the perimeter of a square with side 5?", "options": {"A": "15", "B": "20", "C": "25", "D": "10"}, "answer": "B"},
    {"difficulty": "Easy", "question": "Which is the smallest prime number?", "options": {"A": "0", "B": "1", "C": "2", "D": "3"}, "answer": "C"},
    {"difficulty": "Easy", "question": "What is 9 x 9?", "options": {"A": "72", "B": "81", "C": "90", "D": "99"}, "answer": "B"},
    {"difficulty": "Easy", "question": "How many seconds in a minute?", "options": {"A": "30", "B": "45", "C": "60", "D": "90"}, "answer": "C"},
    {"difficulty": "Easy", "question": "What is the next: 5, 10, 15, 20, ?", "options": {"A": "22", "B": "24", "C": "25", "D": "30"}, "answer": "C"},
    {"difficulty": "Easy", "question": "Which shape has 3 sides?", "options": {"A": "Square", "B": "Triangle", "C": "Rectangle", "D": "Circle"}, "answer": "B"},
    {"difficulty": "Easy", "question": "What is 6 + 7 x 2?", "options": {"A": "26", "B": "20", "C": "19", "D": "25"}, "answer": "B"},
    {"difficulty": "Easy", "question": "Which is not a programming language: Python, Java, HTML, C++?", "options": {"A": "Python", "B": "Java", "C": "HTML", "D": "C++"}, "answer": "C"},
    {"difficulty": "Easy", "question": "What does HTTP stand for?", "options": {"A": "HyperText Transfer Protocol", "B": "High Transfer Text Protocol", "C": "HyperText Transmission Protocol", "D": "High Text Transfer Protocol"}, "answer": "A"},
    {"difficulty": "Easy", "question": "How many days in a leap year?", "options": {"A": "364", "B": "365", "C": "366", "D": "367"}, "answer": "C"},
    {"difficulty": "Easy", "question": "What is the area of a rectangle 4x5?", "options": {"A": "16", "B": "18", "C": "20", "D": "22"}, "answer": "C"},
    {"difficulty": "Easy", "question": "Which is the fastest land animal?", "options": {"A": "Lion", "B": "Cheetah", "C": "Horse", "D": "Tiger"}, "answer": "B"},
    {"difficulty": "Easy", "question": "What is 144 / 12?", "options": {"A": "10", "B": "11", "C": "12", "D": "13"}, "answer": "C"},
    {"difficulty": "Easy", "question": "Next in series: 2, 4, 6, 8, ?", "options": {"A": "9", "B": "10", "C": "11", "D": "12"}, "answer": "B"},
    {"difficulty": "Easy", "question": "Which is the odd one out: Cat, Dog, Rose, Cow?", "options": {"A": "Cat", "B": "Dog", "C": "Rose", "D": "Cow"}, "answer": "C"},
    {"difficulty": "Easy", "question": "What is 3 squared?", "options": {"A": "6", "B": "8", "C": "9", "D": "12"}, "answer": "C"},
    {"difficulty": "Easy", "question": "How many months have 31 days?", "options": {"A": "5", "B": "6", "C": "7", "D": "8"}, "answer": "C"},
    {"difficulty": "Easy", "question": "What is 1000 - 250?", "options": {"A": "650", "B": "700", "C": "750", "D": "800"}, "answer": "C"},
    {"difficulty": "Easy", "question": "Which direction is opposite to North?", "options": {"A": "East", "B": "West", "C": "South", "D": "Northeast"}, "answer": "C"},
    {"difficulty": "Easy", "question": "What is the next: 100, 90, 80, 70, ?", "options": {"A": "55", "B": "60", "C": "65", "D": "70"}, "answer": "B"},
    {"difficulty": "Easy", "question": "What is 5! (5 factorial)?", "options": {"A": "60", "B": "100", "C": "120", "D": "150"}, "answer": "C"},
    {"difficulty": "Easy", "question": "Which is larger: 3/4 or 2/3?", "options": {"A": "2/3", "B": "3/4", "C": "Equal", "D": "Cannot say"}, "answer": "B"},
    {"difficulty": "Easy", "question": "What is 20% of 500?", "options": {"A": "80", "B": "90", "C": "100", "D": "110"}, "answer": "C"},
    {"difficulty": "Easy", "question": "If x = 3, what is 2x + 4?", "options": {"A": "8", "B": "9", "C": "10", "D": "12"}, "answer": "C"},
    {"difficulty": "Easy", "question": "How many zeros in one million?", "options": {"A": "5", "B": "6", "C": "7", "D": "8"}, "answer": "B"},
    {"difficulty": "Easy", "question": "What is the next prime after 7?", "options": {"A": "8", "B": "9", "C": "10", "D": "11"}, "answer": "D"},
    {"difficulty": "Easy", "question": "Which is heavier: 1kg iron or 1kg cotton?", "options": {"A": "Iron", "B": "Cotton", "C": "Both equal", "D": "Cannot say"}, "answer": "C"},
    {"difficulty": "Easy", "question": "What is 75 + 25?", "options": {"A": "90", "B": "95", "C": "100", "D": "105"}, "answer": "C"},
    {"difficulty": "Easy", "question": "Next: 1, 2, 4, 7, 11, ?", "options": {"A": "14", "B": "15", "C": "16", "D": "17"}, "answer": "C"},
    {"difficulty": "Easy", "question": "How many faces does a cube have?", "options": {"A": "4", "B": "5", "C": "6", "D": "8"}, "answer": "C"},
    {"difficulty": "Easy", "question": "What is 2 to the power of 8?", "options": {"A": "128", "B": "256", "C": "512", "D": "64"}, "answer": "B"},
    {"difficulty": "Easy", "question": "Which is odd: 2, 4, 6, 7, 8?", "options": {"A": "2", "B": "4", "C": "7", "D": "8"}, "answer": "C"},
    {"difficulty": "Easy", "question": "What is 33% of 300?", "options": {"A": "66", "B": "99", "C": "100", "D": "110"}, "answer": "B"},
    {"difficulty": "Easy", "question": "How many weeks in a year?", "options": {"A": "48", "B": "50", "C": "52", "D": "54"}, "answer": "C"},

    # ==================== MEDIUM (65 questions) ====================
    {"difficulty": "Medium", "question": "If 5 machines take 5 minutes to make 5 products, how long will 100 machines take to make 100 products?", "options": {"A": "5 minutes", "B": "10 minutes", "C": "100 minutes", "D": "1 minute"}, "answer": "A"},
    {"difficulty": "Medium", "question": "If 6 workers can build a wall in 10 days, how many days will 3 workers take?", "options": {"A": "5", "B": "15", "C": "20", "D": "12"}, "answer": "C"},
    {"difficulty": "Medium", "question": "If 3x + 6 = 18, what is x?", "options": {"A": "2", "B": "3", "C": "4", "D": "6"}, "answer": "C"},
    {"difficulty": "Medium", "question": "All roses are flowers. All flowers fade. Therefore:", "options": {"A": "All flowers are roses", "B": "Some roses fade", "C": "All roses fade", "D": "None of the above"}, "answer": "C"},
    {"difficulty": "Medium", "question": "If the average of 5 numbers is 20, what is their sum?", "options": {"A": "80", "B": "90", "C": "100", "D": "110"}, "answer": "C"},
    {"difficulty": "Medium", "question": "If 40% of a number is 80, what is the number?", "options": {"A": "150", "B": "175", "C": "200", "D": "225"}, "answer": "C"},
    {"difficulty": "Medium", "question": "Next in series: 2, 5, 10, 17, 26, ?", "options": {"A": "35", "B": "36", "C": "37", "D": "38"}, "answer": "C"},
    {"difficulty": "Medium", "question": "Find the next: 100, 50, 25, 12.5, ?", "options": {"A": "5", "B": "6", "C": "6.25", "D": "7"}, "answer": "C"},
    {"difficulty": "Medium", "question": "What is the next: 2, 6, 18, 54, ?", "options": {"A": "108", "B": "162", "C": "216", "D": "270"}, "answer": "B"},
    {"difficulty": "Medium", "question": "Find the odd one out: 121, 144, 169, 196, 200", "options": {"A": "121", "B": "169", "C": "200", "D": "196"}, "answer": "C"},
    {"difficulty": "Medium", "question": "A car covers 180 km in 3 hours. What is its speed?", "options": {"A": "40", "B": "50", "C": "60", "D": "70"}, "answer": "C"},
    {"difficulty": "Medium", "question": "If A = 1, B = 2, C = 3, what is D + E?", "options": {"A": "7", "B": "8", "C": "9", "D": "10"}, "answer": "C"},
    {"difficulty": "Medium", "question": "A shopkeeper buys at 80 and sells at 100. Profit %?", "options": {"A": "20%", "B": "25%", "C": "15%", "D": "10%"}, "answer": "B"},
    {"difficulty": "Medium", "question": "If 2x - 3 = 11, what is x?", "options": {"A": "5", "B": "6", "C": "7", "D": "8"}, "answer": "C"},
    {"difficulty": "Medium", "question": "A pipe fills a tank in 4 hours. How much in 1 hour?", "options": {"A": "1/3", "B": "1/4", "C": "1/5", "D": "1/6"}, "answer": "B"},
    {"difficulty": "Medium", "question": "What is the probability of getting heads in a coin toss?", "options": {"A": "1/4", "B": "1/3", "C": "1/2", "D": "2/3"}, "answer": "C"},
    {"difficulty": "Medium", "question": "If a rectangle has area 48 and width 6, what is length?", "options": {"A": "6", "B": "7", "C": "8", "D": "9"}, "answer": "C"},
    {"difficulty": "Medium", "question": "What is 12% of 1500?", "options": {"A": "150", "B": "170", "C": "180", "D": "200"}, "answer": "C"},
    {"difficulty": "Medium", "question": "Find the missing: 2, 3, 5, 7, 11, 13, ?", "options": {"A": "15", "B": "16", "C": "17", "D": "18"}, "answer": "C"},
    {"difficulty": "Medium", "question": "If speed is 45 km/h, time to cover 135 km?", "options": {"A": "2 hrs", "B": "3 hrs", "C": "4 hrs", "D": "5 hrs"}, "answer": "B"},
    {"difficulty": "Medium", "question": "What is the compound interest on 1000 at 10% for 2 years?", "options": {"A": "200", "B": "210", "C": "220", "D": "250"}, "answer": "B"},
    {"difficulty": "Medium", "question": "If 30% of x = 90, then x = ?", "options": {"A": "200", "B": "250", "C": "300", "D": "350"}, "answer": "C"},
    {"difficulty": "Medium", "question": "A work done by A in 10 days, B in 15 days. Together?", "options": {"A": "5 days", "B": "6 days", "C": "7 days", "D": "8 days"}, "answer": "B"},
    {"difficulty": "Medium", "question": "What is the next: 3, 9, 27, 81, ?", "options": {"A": "162", "B": "243", "C": "324", "D": "405"}, "answer": "B"},
    {"difficulty": "Medium", "question": "If selling price is 120 and cost price is 100, profit%?", "options": {"A": "10%", "B": "15%", "C": "20%", "D": "25%"}, "answer": "C"},
    {"difficulty": "Medium", "question": "What is the median of: 3, 7, 2, 9, 5?", "options": {"A": "3", "B": "5", "C": "7", "D": "9"}, "answer": "B"},
    {"difficulty": "Medium", "question": "How many diagonals does a pentagon have?", "options": {"A": "3", "B": "4", "C": "5", "D": "6"}, "answer": "C"},
    {"difficulty": "Medium", "question": "If P is 5 more than Q and Q = 10, what is P + Q?", "options": {"A": "20", "B": "25", "C": "30", "D": "35"}, "answer": "B"},
    {"difficulty": "Medium", "question": "A number when doubled and added 6 gives 20. Number?", "options": {"A": "5", "B": "6", "C": "7", "D": "8"}, "answer": "C"},
    {"difficulty": "Medium", "question": "What is the mode of: 2, 3, 3, 4, 5, 3, 2?", "options": {"A": "2", "B": "3", "C": "4", "D": "5"}, "answer": "B"},
    {"difficulty": "Medium", "question": "Distance = Speed x Time. If speed=60, time=2.5hrs, distance=?", "options": {"A": "120", "B": "140", "C": "150", "D": "160"}, "answer": "C"},
    {"difficulty": "Medium", "question": "What is 15 squared?", "options": {"A": "175", "B": "200", "C": "225", "D": "250"}, "answer": "C"},
    {"difficulty": "Medium", "question": "A train 100m long passes a pole in 10 sec. Speed in m/s?", "options": {"A": "5", "B": "8", "C": "10", "D": "12"}, "answer": "C"},
    {"difficulty": "Medium", "question": "If ratio of A:B = 3:4 and total = 70, what is A?", "options": {"A": "28", "B": "30", "C": "32", "D": "35"}, "answer": "B"},
    {"difficulty": "Medium", "question": "What is 35% of 80?", "options": {"A": "24", "B": "26", "C": "28", "D": "30"}, "answer": "C"},
    {"difficulty": "Medium", "question": "If area of circle is 154, what is radius? (π=22/7)", "options": {"A": "5", "B": "6", "C": "7", "D": "8"}, "answer": "C"},
    {"difficulty": "Medium", "question": "What is next in: 1, 4, 9, 16, 25, ?", "options": {"A": "30", "B": "34", "C": "36", "D": "49"}, "answer": "C"},
    {"difficulty": "Medium", "question": "Simple interest on 2000 at 5% for 3 years?", "options": {"A": "200", "B": "250", "C": "300", "D": "350"}, "answer": "C"},
    {"difficulty": "Medium", "question": "If cost price = 250 and loss = 10%, selling price?", "options": {"A": "215", "B": "220", "C": "225", "D": "230"}, "answer": "C"},
    {"difficulty": "Medium", "question": "What is the sum of first 10 natural numbers?", "options": {"A": "45", "B": "50", "C": "55", "D": "60"}, "answer": "C"},
    {"difficulty": "Medium", "question": "Two numbers are in ratio 5:3. Sum = 160. Larger number?", "options": {"A": "90", "B": "95", "C": "100", "D": "110"}, "answer": "C"},
    {"difficulty": "Medium", "question": "What is 2^10?", "options": {"A": "512", "B": "1024", "C": "2048", "D": "256"}, "answer": "B"},
    {"difficulty": "Medium", "question": "A clock shows 3:15. Angle between hands?", "options": {"A": "0°", "B": "7.5°", "C": "15°", "D": "22.5°"}, "answer": "B"},
    {"difficulty": "Medium", "question": "If 5 apples cost Rs 20, cost of 8 apples?", "options": {"A": "28", "B": "30", "C": "32", "D": "35"}, "answer": "C"},
    {"difficulty": "Medium", "question": "What is next: 0, 1, 1, 2, 3, 5, 8, ?", "options": {"A": "11", "B": "12", "C": "13", "D": "14"}, "answer": "C"},
    {"difficulty": "Medium", "question": "Volume of a cube with side 3?", "options": {"A": "9", "B": "18", "C": "27", "D": "36"}, "answer": "C"},
    {"difficulty": "Medium", "question": "What is 45 x 45?", "options": {"A": "1925", "B": "2000", "C": "2025", "D": "2050"}, "answer": "C"},
    {"difficulty": "Medium", "question": "A person walks 4km North then 3km East. Total distance from start?", "options": {"A": "4km", "B": "5km", "C": "6km", "D": "7km"}, "answer": "B"},
    {"difficulty": "Medium", "question": "Which is largest: 5/8, 7/10, 3/5, 2/3?", "options": {"A": "5/8", "B": "7/10", "C": "3/5", "D": "2/3"}, "answer": "B"},
    {"difficulty": "Medium", "question": "What is the next: 1, 8, 27, 64, ?", "options": {"A": "100", "B": "115", "C": "125", "D": "150"}, "answer": "C"},
    {"difficulty": "Medium", "question": "A bag has 3 red, 4 blue balls. Probability of red?", "options": {"A": "3/4", "B": "3/7", "C": "4/7", "D": "1/2"}, "answer": "B"},
    {"difficulty": "Medium", "question": "What is the sum of angles in a triangle?", "options": {"A": "90°", "B": "180°", "C": "270°", "D": "360°"}, "answer": "B"},
    {"difficulty": "Medium", "question": "If x/5 = 4, what is x?", "options": {"A": "15", "B": "20", "C": "25", "D": "30"}, "answer": "B"},
    {"difficulty": "Medium", "question": "A man's salary increased by 20% to 36000. Original salary?", "options": {"A": "28000", "B": "30000", "C": "32000", "D": "34000"}, "answer": "B"},
    {"difficulty": "Medium", "question": "What is the next prime after 13?", "options": {"A": "15", "B": "16", "C": "17", "D": "19"}, "answer": "C"},
    {"difficulty": "Medium", "question": "LCM of 12, 15, and 20?", "options": {"A": "30", "B": "45", "C": "60", "D": "90"}, "answer": "C"},
    {"difficulty": "Medium", "question": "Next in: 2, 3, 5, 8, 13, 21, ?", "options": {"A": "30", "B": "32", "C": "34", "D": "36"}, "answer": "C"},
    {"difficulty": "Medium", "question": "What is 0.25 as a fraction?", "options": {"A": "1/2", "B": "1/3", "C": "1/4", "D": "1/5"}, "answer": "C"},
    {"difficulty": "Medium", "question": "If 20 men do a work in 15 days, 30 men do it in?", "options": {"A": "8 days", "B": "10 days", "C": "12 days", "D": "15 days"}, "answer": "B"},
    {"difficulty": "Medium", "question": "What is the average of 10, 20, 30, 40, 50?", "options": {"A": "25", "B": "30", "C": "35", "D": "40"}, "answer": "B"},
    {"difficulty": "Medium", "question": "Circumference of circle with radius 7? (π=22/7)", "options": {"A": "22", "B": "44", "C": "66", "D": "88"}, "answer": "B"},
    {"difficulty": "Medium", "question": "Which is NOT a type of triangle: Equilateral, Scalene, Isosceles, Quadrant?", "options": {"A": "Equilateral", "B": "Scalene", "C": "Isosceles", "D": "Quadrant"}, "answer": "D"},
    {"difficulty": "Medium", "question": "What is 75% of 200?", "options": {"A": "125", "B": "140", "C": "150", "D": "160"}, "answer": "C"},
    {"difficulty": "Medium", "question": "If a = 2, b = 3, find a^2 + b^2?", "options": {"A": "10", "B": "12", "C": "13", "D": "15"}, "answer": "C"},
    {"difficulty": "Medium", "question": "What is the next: 1, 3, 7, 15, 31, ?", "options": {"A": "55", "B": "60", "C": "63", "D": "65"}, "answer": "C"},

    # ==================== HARD (65 questions) ====================
    {"difficulty": "Hard", "question": "What is the time complexity of binary search?", "options": {"A": "O(n)", "B": "O(n²)", "C": "O(log n)", "D": "O(n log n)"}, "answer": "C"},
    {"difficulty": "Hard", "question": "Which sorting algorithm has worst case O(n log n)?", "options": {"A": "Bubble Sort", "B": "Quick Sort", "C": "Merge Sort", "D": "Insertion Sort"}, "answer": "C"},
    {"difficulty": "Hard", "question": "What is a deadlock in operating systems?", "options": {"A": "Memory overflow", "B": "Two processes waiting for each other", "C": "CPU crash", "D": "Disk failure"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What does SQL JOIN do?", "options": {"A": "Deletes rows", "B": "Combines rows from two tables", "C": "Creates a new table", "D": "Updates records"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is a binary tree?", "options": {"A": "Tree with 2 roots", "B": "Tree where each node has at most 2 children", "C": "Tree with 2 levels", "D": "Tree with exactly 2 nodes"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is polymorphism in OOP?", "options": {"A": "Multiple inheritance", "B": "One class, multiple forms", "C": "Hiding data", "D": "Code reuse"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is the output of 5 // 2 in Python?", "options": {"A": "2.5", "B": "3", "C": "2", "D": "1"}, "answer": "C"},
    {"difficulty": "Hard", "question": "What is normalization in databases?", "options": {"A": "Encrypting data", "B": "Reducing data redundancy", "C": "Increasing table size", "D": "Backing up data"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is an API?", "options": {"A": "A programming language", "B": "Application Programming Interface", "C": "A database", "D": "A server"}, "answer": "B"},
    {"difficulty": "Hard", "question": "Which HTTP method is used to update data?", "options": {"A": "GET", "B": "POST", "C": "PUT", "D": "DELETE"}, "answer": "C"},
    {"difficulty": "Hard", "question": "What is Big O notation used for?", "options": {"A": "Measuring memory", "B": "Describing algorithm complexity", "C": "Counting bugs", "D": "Network speed"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is recursion?", "options": {"A": "A loop", "B": "A function calling itself", "C": "A data structure", "D": "An error type"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What does OOP stand for?", "options": {"A": "Object Oriented Programming", "B": "Open Oriented Processing", "C": "Object Output Processing", "D": "Oriented Object Programming"}, "answer": "A"},
    {"difficulty": "Hard", "question": "What is a hash table?", "options": {"A": "A sorted array", "B": "Key-value storage with fast lookup", "C": "A linked list", "D": "A binary tree"}, "answer": "B"},
    {"difficulty": "Hard", "question": "Which is NOT a NoSQL database?", "options": {"A": "MongoDB", "B": "Redis", "C": "MySQL", "D": "Cassandra"}, "answer": "C"},
    {"difficulty": "Hard", "question": "What is the purpose of an index in a database?", "options": {"A": "Store backup", "B": "Speed up queries", "C": "Encrypt data", "D": "Delete duplicates"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is encapsulation in OOP?", "options": {"A": "Multiple inheritance", "B": "Hiding internal details", "C": "Method overloading", "D": "Code reuse"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is a stack overflow?", "options": {"A": "Memory leak", "B": "Too many recursive calls", "C": "Database error", "D": "Network timeout"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is the difference between TCP and UDP?", "options": {"A": "TCP is faster", "B": "TCP is reliable, UDP is fast but unreliable", "C": "UDP is reliable", "D": "No difference"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is a foreign key?", "options": {"A": "A primary key in another table", "B": "An encrypted key", "C": "A unique identifier", "D": "A backup key"}, "answer": "A"},
    {"difficulty": "Hard", "question": "What is the purpose of Git?", "options": {"A": "Run programs", "B": "Version control", "C": "Design UI", "D": "Manage databases"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is inheritance in OOP?", "options": {"A": "Data hiding", "B": "Child class getting properties of parent", "C": "Multiple instances", "D": "Method overloading"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is REST?", "options": {"A": "A database", "B": "Representational State Transfer", "C": "A programming language", "D": "A protocol"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What does DNS stand for?", "options": {"A": "Domain Name System", "B": "Data Network Service", "C": "Dynamic Network System", "D": "Domain Network Service"}, "answer": "A"},
    {"difficulty": "Hard", "question": "What is a linked list?", "options": {"A": "An array of links", "B": "Nodes connected by pointers", "C": "A sorted array", "D": "A hash table"}, "answer": "B"},
    {"difficulty": "Hard", "question": "Which is used for asynchronous programming in Python?", "options": {"A": "threading", "B": "multiprocessing", "C": "asyncio", "D": "subprocess"}, "answer": "C"},
    {"difficulty": "Hard", "question": "What is the purpose of a constructor?", "options": {"A": "Destroy objects", "B": "Initialize objects", "C": "Copy objects", "D": "Compare objects"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is virtual memory?", "options": {"A": "RAM extension using disk", "B": "A type of ROM", "C": "CPU cache", "D": "GPU memory"}, "answer": "A"},
    {"difficulty": "Hard", "question": "What is a race condition?", "options": {"A": "Fast algorithm", "B": "Two threads accessing same resource simultaneously", "C": "Memory overflow", "D": "Network latency"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What does SOLID stand for in software?", "options": {"A": "A set of design principles", "B": "A programming language", "C": "A framework", "D": "A database standard"}, "answer": "A"},
    {"difficulty": "Hard", "question": "What is the difference between == and === in JavaScript?", "options": {"A": "No difference", "B": "=== checks type too", "C": "== is stricter", "D": "=== is for strings only"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is memoization?", "options": {"A": "Memory management", "B": "Caching function results", "C": "Memory allocation", "D": "Garbage collection"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is a microservice?", "options": {"A": "A small computer", "B": "Independent deployable service", "C": "A mini database", "D": "A UI component"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is Docker used for?", "options": {"A": "Version control", "B": "Containerization", "C": "UI design", "D": "Database management"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is the purpose of middleware?", "options": {"A": "UI rendering", "B": "Processing requests between client and server", "C": "Database storage", "D": "File compression"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is a closure in programming?", "options": {"A": "A loop", "B": "Function with access to outer scope variables", "C": "A class method", "D": "An interface"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is the CAP theorem?", "options": {"A": "CPU, API, Protocol", "B": "Consistency, Availability, Partition tolerance", "C": "Cache, Array, Pointer", "D": "Copy, Assign, Parse"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is a mutex?", "options": {"A": "A data type", "B": "Mutual exclusion lock", "C": "Memory unit", "D": "Network protocol"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is lazy loading?", "options": {"A": "Slow loading", "B": "Loading resources only when needed", "C": "Preloading all data", "D": "Caching data"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is the purpose of JWT?", "options": {"A": "JavaScript Wrapper Token", "B": "JSON Web Token for authentication", "C": "Java Web Toolkit", "D": "JSON Widget Tool"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is a design pattern?", "options": {"A": "UI template", "B": "Reusable solution to common problem", "C": "Database schema", "D": "Code syntax"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is the Observer pattern?", "options": {"A": "Watch CPU usage", "B": "Object notifies dependents of state changes", "C": "Monitor network", "D": "Log errors"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is dependency injection?", "options": {"A": "Adding libraries", "B": "Passing dependencies from outside", "C": "Injecting SQL", "D": "Adding plugins"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is the Singleton pattern?", "options": {"A": "Only one method", "B": "Only one instance of a class", "C": "Single thread", "D": "Single database"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is graph traversal BFS?", "options": {"A": "Depth first search", "B": "Breadth first search", "C": "Binary file search", "D": "Best first search"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is the purpose of load balancing?", "options": {"A": "Reduce code size", "B": "Distribute traffic across servers", "C": "Balance database", "D": "Manage memory"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is ACID in databases?", "options": {"A": "A query language", "B": "Atomicity, Consistency, Isolation, Durability", "C": "A data type", "D": "An index type"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is the purpose of a CDN?", "options": {"A": "Code Delivery Network", "B": "Content Delivery Network", "C": "Central Data Node", "D": "Core DNS Node"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is event-driven architecture?", "options": {"A": "UI events only", "B": "System reacts to events/messages", "C": "Calendar-based system", "D": "Log-based system"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is the difference between process and thread?", "options": {"A": "No difference", "B": "Process is independent, thread shares memory", "C": "Thread is heavier", "D": "Process is faster"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is a callback function?", "options": {"A": "A return value", "B": "Function passed as argument, called later", "C": "A recursive function", "D": "An error handler"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is the purpose of hashing in security?", "options": {"A": "Encrypt data reversibly", "B": "One-way transformation of data", "C": "Compress data", "D": "Copy data"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is a promise in JavaScript?", "options": {"A": "A guarantee", "B": "Object for async operations", "C": "A variable type", "D": "A loop construct"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is sharding in databases?", "options": {"A": "Deleting old data", "B": "Splitting data across multiple servers", "C": "Encrypting data", "D": "Backing up data"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is the purpose of an ORM?", "options": {"A": "Object Relational Mapping", "B": "Open Resource Manager", "C": "Output Rendering Module", "D": "Online Request Manager"}, "answer": "A"},
    {"difficulty": "Hard", "question": "What is a webhook?", "options": {"A": "A fishing tool", "B": "HTTP callback triggered by event", "C": "A web framework", "D": "A browser plugin"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is idempotency in REST APIs?", "options": {"A": "Fast response", "B": "Same request gives same result", "C": "Cached response", "D": "Encrypted request"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is the purpose of Redis?", "options": {"A": "File storage", "B": "In-memory data store/cache", "C": "Image processing", "D": "Email service"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is a monolithic architecture?", "options": {"A": "Single server", "B": "All components in one deployable unit", "C": "One database", "D": "One programming language"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is CI/CD?", "options": {"A": "Code Integration/Code Deployment", "B": "Continuous Integration/Continuous Deployment", "C": "Central Interface/Central Database", "D": "Code Inspection/Code Debug"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is the purpose of Kubernetes?", "options": {"A": "Version control", "B": "Container orchestration", "C": "UI framework", "D": "Database management"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is a Graph data structure?", "options": {"A": "A chart", "B": "Nodes connected by edges", "C": "A sorted list", "D": "A matrix"}, "answer": "B"},
    {"difficulty": "Hard", "question": "What is the time complexity of bubble sort?", "options": {"A": "O(n)", "B": "O(n log n)", "C": "O(n²)", "D": "O(log n)"}, "answer": "C"},
    {"difficulty": "Hard", "question": "What is a semaphore?", "options": {"A": "A signal system", "B": "Synchronization primitive for resource access", "C": "A network protocol", "D": "A data type"}, "answer": "B"},
]

INTERVIEW_QUESTIONS = {
    "DataAnalysis": [
        "How do you handle missing or inconsistent data during data analysis?",
        "What is normalization and why is it important in data preprocessing?",
        "Explain exploratory data analysis (EDA) and its key steps.",
        "Which tools or libraries do you use for data visualization and why?",
        "How do you deal with outliers in a dataset?",
        "Explain the difference between correlation and causation.",
        "What is feature engineering and how does it improve model performance?",
        "How would you handle a highly imbalanced dataset?",
        "What is the difference between OLAP and OLTP systems?",
        "Explain the concept of A/B testing and when you would use it."
    ],
    "WebDevelopment": [
        "What is HTML and what is its role in web development?",
        "What is CSS and how do you use it to style web pages?",
        "Explain the difference between GET and POST HTTP methods.",
        "What is responsive web design and how do you implement it?",
        "Can you explain the concept of DOM in JavaScript?",
        "What is the difference between localStorage and sessionStorage?",
        "Explain the concept of RESTful APIs and their principles.",
        "What is CORS and why is it important in web development?",
        "How does the browser render a webpage from HTML to display?",
        "What are React hooks and how do useState and useEffect work?"
    ],
    "MachineLearning": [
        "What is supervised learning and unsupervised learning?",
        "Explain the difference between classification and regression.",
        "What is overfitting and how can you prevent it?",
        "What is the purpose of cross-validation in ML?",
        "Can you explain a machine learning project you have done?",
        "What is the bias-variance tradeoff?",
        "Explain how a decision tree works.",
        "What is gradient descent and how does it optimize models?",
        "What is the difference between bagging and boosting?",
        "How would you evaluate the performance of a classification model?"
    ],
    "CyberSecurity": [
        "What is the difference between encryption and hashing?",
        "What are the common types of cyber attacks?",
        "Explain what a firewall does and its types.",
        "What is social engineering in cybersecurity?",
        "How do you secure a network from unauthorized access?",
        "What is a man-in-the-middle attack?",
        "Explain the concept of zero-trust security model.",
        "What is SQL injection and how do you prevent it?",
        "What is the difference between IDS and IPS?",
        "How does HTTPS work and why is it important?"
    ],
    "SoftwareDevelopment": [
        "What is the difference between agile and waterfall methodology?",
        "Explain the SOLID principles in software development.",
        "What is version control and why is Git important?",
        "What is the difference between unit testing and integration testing?",
        "Explain the concept of design patterns with an example.",
        "What is CI/CD and how does it improve software delivery?",
        "What is the difference between monolithic and microservices architecture?",
        "How do you ensure code quality in a team project?",
        "What is refactoring and when should you do it?",
        "Explain the concept of technical debt and how to manage it."
    ],
    "ArtificialIntelligence": [
        "What is the difference between AI, Machine Learning, and Deep Learning?",
        "Explain how a neural network works.",
        "What is natural language processing (NLP)?",
        "What is reinforcement learning and how does it work?",
        "Explain the concept of transfer learning.",
        "What are the ethical concerns around AI development?",
        "What is the difference between narrow AI and general AI?",
        "How does a convolutional neural network (CNN) work?",
        "What is the role of training data in AI model performance?",
        "What is prompt engineering and why is it important for LLMs?"
    ]
}

FIELDS = list(INTERVIEW_QUESTIONS.keys())